local r = {}
local function p(label, fn)
  local ok, val = pcall(fn)
  r[#r+1] = string.format("%s\t%s\t%s",
    ok and "OK" or "ERR", label, tostring(val))
end
p("Player.GetLocalPlayer()", function() return Player.GetLocalPlayer() end)
p("Player.GetLocalCharacter()", function() return Player.GetLocalCharacter() end)
p("Player.GetCash()", function() return Player.GetCash() end)
p("Player.GetFuel()", function() return Player.GetFuel() end)
p("Player.GetFuelCapacity()", function() return Player.GetFuelCapacity() end)
p("Player.GetCurrentPlayers()", function() return Player.GetCurrentPlayers() end)
p("Player.GetMaximumPlayers()", function() return Player.GetMaximumPlayers() end)
p("Player.GetLocalId()", function() return Player.GetLocalId() end)
p("Player.GetName()", function() return Player.GetName() end)
p("Sys.GetLevelName()", function() return Sys.GetLevelName() end)
p("Sys.GetVersion()", function() return Sys.GetVersion() end)
p("Sys.GetPlatform()", function() return Sys.GetPlatform() end)
p("Sys.GetLanguage()", function() return Sys.GetLanguage() end)
p("Sys.GetMasterScriptName()", function() return Sys.GetMasterScriptName() end)
p("Sys.MemUsage()", function() return Sys.MemUsage() end)
p("Sys.RealTime()", function() return Sys.RealTime() end)
p("Sys.MainTime()", function() return Sys.MainTime() end)
p("Sys.Clock()", function() return Sys.Clock() end)
p("Sys.IsLoadingOrStreaming()", function() return Sys.IsLoadingOrStreaming() end)
p("Sys.HaveActiveProfile()", function() return Sys.HaveActiveProfile() end)
p("Sys.IsDemoMode()", function() return Sys.IsDemoMode() end)
p("Sys.IsFinalConfig()", function() return Sys.IsFinalConfig() end)
p("Net.IsServer()", function() return Net.IsServer() end)
p("Net.IsClient()", function() return Net.IsClient() end)
p("Net.IsMultiplayer()", function() return Net.IsMultiplayer() end)
p("Net.IsActive()", function() return Net.IsActive() end)
p("Net.GetHostName()", function() return Net.GetHostName() end)
p("Net.IsOnlineConnected()", function() return Net.IsOnlineConnected() end)
return table.concat(r, "\n")
